/* ============================================================
   O LEVEL HUB — PRACTICE QUESTION BANK
   ------------------------------------------------------------
   IMPORTANT — READ THIS.
   These are ORIGINAL questions written in Cambridge exam style.
   They are NOT copied from real past papers.
   They copy the *pattern* of real questions: the command words,
   the mark allocations, the way parts build up, and the way the
   mark scheme awards each mark.
   For REAL questions, use the topical past-paper links on every
   topic — those come with official Cambridge mark schemes.
   ------------------------------------------------------------
   Structure:
     QUESTIONS[subjectId][topicIndex] = [ question, question, ... ]
     question = { cmd, q, m, ms:[...], trap (optional) }
       cmd  = command word, so students learn to spot them
       m    = marks available
       ms   = mark scheme, one string per mark point
       trap = the mistake most students make
   ============================================================ */

const QUESTIONS = {

/* ==========================================================
   PHYSICS 5054
   ========================================================== */
physics: {

/* --- 0. Motion, forces and energy --- */
0: [
  { cmd:"Define", m:2, q:"Define <b>acceleration</b> and state its SI unit.",
    ms:["Acceleration is the rate of change of velocity (1)","SI unit: m/s² (or m s⁻²) (1)"],
    trap:"Writing 'change of velocity' without 'rate of'. The word 'rate' means per unit time and is worth the mark on its own." },
  { cmd:"State", m:1, q:"State the difference between <b>speed</b> and <b>velocity</b>.",
    ms:["Speed is a scalar (magnitude only); velocity is a vector (magnitude and direction) (1)"],
    trap:"Saying 'velocity has direction' alone is usually accepted, but naming scalar/vector is safer." },
  { cmd:"Calculate", m:3, q:"A car accelerates uniformly from rest to 24 m/s in 8.0 s.<br>Calculate (i) its acceleration, (ii) the distance travelled in this time.",
    ms:["a = (v − u)/t = (24 − 0)/8.0 (1)","a = 3.0 m/s² (1)","Distance = average speed × time = 12 × 8.0 = 96 m (1)"],
    trap:"Using distance = v × t = 24 × 8 = 192 m. The car was not travelling at 24 m/s the whole time." },
  { cmd:"Describe", m:3, q:"A speed–time graph shows a straight line rising from the origin, then a horizontal line, then a straight line falling to zero.<br>Describe the motion of the object in each of the three stages.",
    ms:["Stage 1: uniform/constant acceleration (speed increasing at a steady rate) (1)","Stage 2: constant speed / zero acceleration (1)","Stage 3: uniform deceleration until it stops (1)"],
    trap:"Writing 'it speeds up, stays, slows down' with no mention of *uniform* or *constant*. The straight lines are what tell you the rate is steady." },
  { cmd:"Explain", m:3, q:"A skydiver falls from a plane. Explain, in terms of the forces acting, why she eventually reaches a constant speed.",
    ms:["Initially weight is greater than air resistance, so she accelerates (1)","As speed increases, air resistance increases (1)","When air resistance equals weight, resultant force is zero, so she falls at constant (terminal) speed (1)"],
    trap:"Saying 'gravity increases' or 'weight decreases'. Weight is constant throughout — only air resistance changes." },
  { cmd:"Calculate", m:3, q:"A force of 150 N acts on a mass of 30 kg which is already moving.<br>A frictional force of 30 N opposes the motion. Calculate the acceleration.",
    ms:["Resultant force = 150 − 30 = 120 N (1)","a = F/m = 120/30 (1)","a = 4.0 m/s² (1)"],
    trap:"Using 150 N instead of the resultant. Always find the resultant force before using F = ma." },
  { cmd:"Explain", m:3, q:"Explain why a passenger in a car moves forward when the car stops suddenly.",
    ms:["The passenger has inertia / tends to continue moving (1)","No (or insufficient) backward force acts on the passenger when the car brakes (1)","So the passenger continues at the original speed while the car slows (1)"],
    trap:"Saying 'a force pushes them forward'. Nothing pushes them forward — that is the whole point of the question." },
  { cmd:"Calculate", m:4, q:"A crane lifts a load of mass 250 kg through a vertical height of 12 m in 20 s. (g = 10 N/kg)<br>Calculate (i) the work done, (ii) the useful power output.",
    ms:["Weight = mg = 250 × 10 = 2500 N (1)","Work = force × distance = 2500 × 12 (1)","Work = 30 000 J (1)","Power = W/t = 30 000/20 = 1500 W (1)"],
    trap:"Using mass (250) instead of weight (2500 N) as the force. Work needs a force in newtons." },
  { cmd:"Describe", m:3, q:"Describe an experiment to find the centre of gravity of an irregular flat sheet of card.",
    ms:["Hang the card freely from a point near its edge, with a plumb line from the same point (1)","Mark the line of the plumb line on the card (1)","Repeat from a different point; the centre of gravity is where the lines cross (1)"],
    trap:"Forgetting to say the card must swing *freely*. If it is held, it will not settle correctly." },
  { cmd:"Explain", m:2, q:"A wide, flat-based bus is more stable than a tall, narrow one. Explain why.",
    ms:["The wide base and low centre of gravity mean the bus can tilt further before the centre of gravity passes outside the base (1)","So the line of action of the weight stays inside the base, giving a restoring moment (1)"],
    trap:"Just saying 'it is heavier at the bottom'. You must link centre of gravity to the edge of the base." }
],

/* --- 1. Thermal physics --- */
1: [
  { cmd:"Describe", m:3, q:"Describe the arrangement and motion of the particles in a <b>solid</b> and in a <b>gas</b>.",
    ms:["Solid: particles closely packed in a regular pattern (1)","Solid: particles vibrate about fixed positions (1)","Gas: particles far apart, random arrangement, moving rapidly in all directions (1)"],
    trap:"Saying solid particles 'do not move'. They vibrate — that is why solids can be heated." },
  { cmd:"Explain", m:3, q:"Explain, in terms of particles, why the pressure of a fixed mass of gas increases when it is heated at constant volume.",
    ms:["Heating increases the average kinetic energy / speed of the particles (1)","Particles collide with the container walls more frequently and with greater force (1)","Force per unit area on the walls increases, so pressure increases (1)"],
    trap:"Only mentioning 'they move faster'. You must reach the *walls* and the *force per unit area* to get all three marks." },
  { cmd:"Calculate", m:3, q:"A gas has a volume of 400 cm³ at a pressure of 1.0 × 10⁵ Pa. The gas is compressed to 250 cm³ at constant temperature.<br>Calculate the new pressure.",
    ms:["Use p₁V₁ = p₂V₂ (1)","p₂ = (1.0 × 10⁵ × 400)/250 (1)","p₂ = 1.6 × 10⁵ Pa (1)"],
    trap:"Converting cm³ to m³ unnecessarily. Because it is a ratio, the units cancel — just keep them the same on both sides." },
  { cmd:"Explain", m:3, q:"Explain, in terms of particles, how thermal energy is transferred through a metal rod by <b>conduction</b>.",
    ms:["Particles at the hot end vibrate more vigorously / gain kinetic energy (1)","They collide with neighbouring particles, passing energy along (1)","In metals, free (delocalised) electrons also carry energy quickly through the metal (1)"],
    trap:"Forgetting free electrons. That is the mark that separates a metal from a non-metal, and questions usually target it." },
  { cmd:"Explain", m:3, q:"Explain why the heating element in an electric kettle is placed at the bottom.",
    ms:["Water near the element is heated and expands, becoming less dense (1)","Less dense water rises and cooler, denser water sinks to take its place (1)","This sets up a convection current which heats all the water (1)"],
    trap:"Saying 'heat rises'. Heat does not rise — the *less dense heated water* rises." },
  { cmd:"State", m:2, q:"State <b>two</b> differences between boiling and evaporation.",
    ms:["Boiling happens at a fixed temperature; evaporation happens at any temperature (1)","Boiling occurs throughout the liquid; evaporation occurs only at the surface (1)"],
    trap:"Giving two versions of the same difference. They must be genuinely separate points." },
  { cmd:"Calculate", m:3, q:"How much thermal energy is needed to raise the temperature of 2.0 kg of water from 20 °C to 80 °C?<br>(specific heat capacity of water = 4200 J/(kg °C))",
    ms:["E = mcΔθ (1)","E = 2.0 × 4200 × (80 − 20) (1)","E = 504 000 J (1)"],
    trap:"Using 80 instead of the temperature *change* of 60. Δθ means the difference, not the final value." },
  { cmd:"Explain", m:2, q:"Explain why evaporation causes cooling of the remaining liquid.",
    ms:["The fastest-moving (most energetic) particles escape from the surface (1)","The average kinetic energy of the remaining particles falls, so the temperature drops (1)"],
    trap:"Saying 'the liquid loses heat'. You need to talk about which particles leave and what that does to the *average* energy." },
  { cmd:"Suggest", m:3, q:"A vacuum flask keeps a hot drink hot. Suggest how its design reduces energy transfer by conduction, convection and radiation.",
    ms:["Vacuum between the walls: no particles, so no conduction or convection through the gap (1)","Silvered surfaces reflect infrared radiation back into the drink (1)","Insulating stopper and supports reduce conduction out of the top (1)"],
    trap:"Naming the features without saying which transfer method each one blocks. The question asks for all three." },
  { cmd:"Explain", m:2, q:"Explain why a black matt surface is a better emitter of infrared radiation than a shiny silver surface.",
    ms:["Black matt surfaces emit infrared radiation at a greater rate than shiny surfaces at the same temperature (1)","Shiny silver surfaces reflect radiation rather than emitting it (1)"],
    trap:"Confusing emitting with absorbing. Black is good at both, but the question asks about emitting." }
],

/* --- 2. Waves --- */
2: [
  { cmd:"Define", m:2, q:"Define the <b>frequency</b> and the <b>wavelength</b> of a wave.",
    ms:["Frequency: the number of complete waves passing a point per second (1)","Wavelength: the distance between two consecutive points in phase, e.g. crest to crest (1)"],
    trap:"Defining wavelength as 'the length of a wave'. You must specify points in phase." },
  { cmd:"Calculate", m:3, q:"A wave has a frequency of 250 Hz and a wavelength of 1.4 m.<br>Calculate its speed, and state how long one complete oscillation takes.",
    ms:["v = fλ = 250 × 1.4 (1)","v = 350 m/s (1)","T = 1/f = 1/250 = 0.004 s (1)"],
    trap:"Forgetting that period and frequency are reciprocals. T = 1/f is worth easy marks." },
  { cmd:"State", m:2, q:"State the <b>law of reflection</b> and explain what is meant by the <b>normal</b>.",
    ms:["The angle of incidence equals the angle of reflection (1)","The normal is a line drawn at 90° to the surface at the point where the ray strikes (1)"],
    trap:"Measuring angles from the surface instead of from the normal. All angles in optics are measured from the normal." },
  { cmd:"Explain", m:3, q:"Explain why a ray of light bends towards the normal when it passes from air into glass.",
    ms:["Light travels more slowly in glass than in air (1)","The change in speed at the boundary causes a change in direction (refraction) (1)","Since it slows down, it bends towards the normal (1)"],
    trap:"Saying 'glass is denser'. Optical density, not mass density, is what matters — but the speed explanation always scores." },
  { cmd:"Calculate", m:3, q:"The critical angle for a glass–air boundary is 42°. Calculate the refractive index of the glass.",
    ms:["n = 1/sin C (1)","n = 1/sin 42° = 1/0.669 (1)","n = 1.49 (accept 1.5) (1)"],
    trap:"Using sin C = 1/n but then forgetting to invert. Write the formula down before substituting." },
  { cmd:"Describe", m:3, q:"Describe the conditions needed for <b>total internal reflection</b> to occur.",
    ms:["Light must be travelling from a denser medium into a less dense medium (1)","The angle of incidence must be greater than the critical angle (1)","No light is refracted out; all of it is reflected back inside (1)"],
    trap:"Saying 'greater than or equal to'. At exactly the critical angle the ray grazes along the boundary — it must be *greater than*." },
  { cmd:"State", m:3, q:"State the seven regions of the electromagnetic spectrum in order of increasing frequency.",
    ms:["Radio waves, microwaves, infrared (1)","Visible light, ultraviolet (1)","X-rays, gamma rays (1)"],
    trap:"Getting the order backwards. Increasing frequency means decreasing wavelength — check which one the question asks for." },
  { cmd:"State", m:2, q:"State <b>one</b> use and <b>one</b> danger of ultraviolet radiation.",
    ms:["Use: detecting forged banknotes / sterilising water / sunbeds (1)","Danger: damage to surface cells, leading to skin cancer or eye damage (1)"],
    trap:"Giving a vague danger like 'it is harmful'. Name the actual damage." },
  { cmd:"Explain", m:3, q:"Explain how an echo is produced and describe how it can be used to measure the depth of the sea.",
    ms:["Sound reflects off a hard surface (the sea bed) and returns (1)","Measure the time t for the sound to travel down and back (1)","Depth = (speed × t)/2, because the sound travels the distance twice (1)"],
    trap:"Forgetting to halve the distance. This single mistake is the most common error in the whole topic." },
  { cmd:"Describe", m:2, q:"Describe how sound travels through air.",
    ms:["Sound is a longitudinal wave: particles vibrate parallel to the direction of travel (1)","It travels as a series of compressions and rarefactions (1)"],
    trap:"Calling sound a transverse wave, or forgetting the words compression and rarefaction." }
],

/* --- 3. Electricity and magnetism --- */
3: [
  { cmd:"Define", m:2, q:"Define <b>electric current</b> and <b>potential difference</b>.",
    ms:["Current is the rate of flow of charge (1)","Potential difference is the work done (energy transferred) per unit charge between two points (1)"],
    trap:"Confusing the two. Current is about charge per second; p.d. is about energy per coulomb. This is the single most confused pair in the syllabus." },
  { cmd:"Calculate", m:3, q:"A charge of 240 C flows through a lamp in 2.0 minutes. The lamp is connected to a 12 V supply.<br>Calculate (i) the current, (ii) the energy transferred.",
    ms:["t = 120 s; I = Q/t = 240/120 = 2.0 A (1)","E = QV = 240 × 12 (1)","E = 2880 J (1)"],
    trap:"Leaving time in minutes. Always convert to seconds before using Q = It." },
  { cmd:"Calculate", m:4, q:"Two resistors, 6.0 Ω and 3.0 Ω, are connected in parallel across a 12 V supply.<br>Calculate the total resistance and the current drawn from the supply.",
    ms:["1/R = 1/6 + 1/3 = 3/6 (1)","R = 2.0 Ω (1)","I = V/R = 12/2.0 (1)","I = 6.0 A (1)"],
    trap:"Forgetting to invert at the end. 1/R = 0.5 means R = 2, not 0.5." },
  { cmd:"State", m:2, q:"State what happens to the total resistance of a circuit when a second resistor is added (i) in series, (ii) in parallel.",
    ms:["In series: total resistance increases (1)","In parallel: total resistance decreases (1)"],
    trap:"Assuming parallel must increase resistance because you added something. Parallel gives the current more paths, so resistance falls." },
  { cmd:"Explain", m:3, q:"Explain why the resistance of a metal wire increases when its temperature rises.",
    ms:["The metal ions vibrate more vigorously at higher temperature (1)","Free electrons collide with the ions more frequently (1)","This makes it harder for charge to flow, so resistance increases (1)"],
    trap:"Saying 'the electrons move slower'. The issue is more frequent collisions, not slower electrons." },
  { cmd:"Explain", m:3, q:"Explain why a fuse and an earth wire together make an appliance with a metal case safe.",
    ms:["If a live wire touches the metal case, the earth wire provides a low-resistance path to earth (1)","A large current flows, which melts the fuse (1)","The fuse breaks the live circuit, disconnecting the appliance and preventing electric shock (1)"],
    trap:"Saying the fuse is in the neutral wire. It must be in the *live* wire, or the appliance stays live after it blows." },
  { cmd:"Describe", m:3, q:"Describe how you would use a plotting compass to show the shape of the magnetic field around a bar magnet.",
    ms:["Place the compass near the magnet and mark the direction the needle points (1)","Move the compass so its tail is where the head was, and repeat to build up a line (1)","Repeat starting from different points; field lines run from north pole to south pole (1)"],
    trap:"Forgetting the arrows. Field lines must have direction, always N to S outside the magnet." },
  { cmd:"State", m:3, q:"State <b>three</b> ways to increase the size of the induced e.m.f. in a simple a.c. generator.",
    ms:["Rotate the coil faster (1)","Use a stronger magnet / stronger magnetic field (1)","Increase the number of turns on the coil (or its area) (1)"],
    trap:"Suggesting 'use a bigger battery'. A generator has no battery — it makes electricity, it does not use it." },
  { cmd:"Calculate", m:3, q:"A transformer has 200 turns on the primary coil and 5000 turns on the secondary. The primary is connected to a 240 V a.c. supply.<br>Calculate the secondary voltage and state whether it is a step-up or step-down transformer.",
    ms:["Vs/Vp = Ns/Np (1)","Vs = 240 × 5000/200 = 6000 V (1)","Step-up transformer (1)"],
    trap:"Inverting the ratio. More turns on the secondary always means a higher secondary voltage." },
  { cmd:"Explain", m:3, q:"Explain why electricity is transmitted across the country at very high voltage.",
    ms:["For a given power, higher voltage means lower current (P = VI) (1)","Power lost as heat in the cables is I²R, so lower current means much less energy wasted (1)","This makes transmission more efficient / cheaper (1)"],
    trap:"Saying 'high voltage means more power gets there'. The power is the same — it is the *loss* that changes." }
],

/* --- 4. Nuclear physics --- */
4: [
  { cmd:"Describe", m:3, q:"Describe the structure of an atom in terms of the nucleus and electrons.",
    ms:["A small, dense, positively charged nucleus at the centre (1)","The nucleus contains protons and neutrons (1)","Electrons orbit the nucleus at a relatively large distance; most of the atom is empty space (1)"],
    trap:"Forgetting to say the nucleus is tiny compared with the atom. That scale point is often the third mark." },
  { cmd:"State", m:2, q:"Explain what is meant by two atoms being <b>isotopes</b> of the same element.",
    ms:["They have the same number of protons (same proton number) (1)","They have different numbers of neutrons (different nucleon number) (1)"],
    trap:"Saying 'different mass'. True, but the marks are for protons and neutrons specifically." },
  { cmd:"State", m:3, q:"State the nature and the penetrating power of alpha, beta and gamma radiation.",
    ms:["Alpha: helium nucleus (2 protons + 2 neutrons), stopped by paper/skin (1)","Beta: fast-moving electron, stopped by a few mm of aluminium (1)","Gamma: high-frequency electromagnetic wave, reduced by thick lead or concrete (1)"],
    trap:"Saying gamma is 'stopped' by lead. It is only reduced — gamma is never fully stopped." },
  { cmd:"Calculate", m:3, q:"A radioactive source has a half-life of 6 hours. Its initial count rate is 800 counts per minute.<br>Calculate the count rate after 24 hours.",
    ms:["24 hours = 4 half-lives (1)","800 → 400 → 200 → 100 → 50 (1)","Count rate = 50 counts per minute (1)"],
    trap:"Dividing by 4 instead of halving 4 times. Half-life is repeated halving, not simple division." },
  { cmd:"Define", m:2, q:"Define the <b>half-life</b> of a radioactive isotope.",
    ms:["The time taken for half the undecayed nuclei in a sample to decay (1)","(Or) the time taken for the activity/count rate to fall to half its original value (1)"],
    trap:"Saying 'the time for the sample to halve in mass'. It is about nuclei decaying, not mass disappearing." },
  { cmd:"Calculate", m:2, q:"Complete this decay equation and name the type of decay:<br>²³⁸U (Z = 92) → ²³⁴Th (Z = 90) + ?",
    ms:["The missing particle is ⁴₂He, an alpha particle (1)","This is alpha decay (1)"],
    trap:"Not checking that both top numbers and both bottom numbers balance. 238 = 234 + 4 and 92 = 90 + 2." },
  { cmd:"Explain", m:2, q:"Explain why background radiation must be measured before an experiment with a radioactive source.",
    ms:["Background radiation is always present from natural sources and contributes to the reading (1)","It must be subtracted from all readings to find the true count rate from the source (1)"],
    trap:"Saying it is 'for safety'. It is for accuracy — the background count corrupts your data if ignored." },
  { cmd:"State", m:2, q:"State the difference between nuclear <b>fission</b> and nuclear <b>fusion</b>.",
    ms:["Fission: a large nucleus splits into two smaller nuclei, releasing energy (1)","Fusion: two small nuclei join to form a larger nucleus, releasing energy (1)"],
    trap:"Mixing up which one happens in the Sun. The Sun does fusion; power stations do fission." },
  { cmd:"Suggest", m:3, q:"Suggest three precautions a worker should take when handling a radioactive source.",
    ms:["Handle with long tongs to increase distance from the source (1)","Limit the time spent near the source (1)","Store in a lead-lined container and wear a film badge to monitor exposure (1)"],
    trap:"Saying 'wear gloves'. Gloves stop contamination but do nothing against gamma — distance, time and shielding are the real answers." },
  { cmd:"Suggest", m:2, q:"A hospital needs a radioactive tracer to be injected into a patient. Suggest, with reasons, which type of radiation and which half-life would be most suitable.",
    ms:["Gamma, because it can penetrate out of the body to be detected (1)","A short half-life, so the activity falls quickly and the patient is not exposed for long (1)"],
    trap:"Choosing alpha because it is 'strong'. Alpha cannot escape the body and does the most damage inside it." }
],

/* --- 5. Space physics --- */
5: [
  { cmd:"Describe", m:3, q:"Describe the structure of the Solar System.",
    ms:["The Sun at the centre, with eight planets orbiting it (1)","Orbits are elliptical; inner planets are rocky, outer planets are gas giants (1)","Also contains moons, asteroids (mainly between Mars and Jupiter) and comets (1)"],
    trap:"Listing planets without describing the structure. The question asks about arrangement, not names." },
  { cmd:"Explain", m:2, q:"Explain why a planet further from the Sun takes longer to complete one orbit.",
    ms:["It has a greater orbital radius, so a longer distance to travel (1)","The gravitational field strength is weaker, so its orbital speed is lower (1)"],
    trap:"Only mentioning the longer distance. Both distance and slower speed are needed for full marks." },
  { cmd:"State", m:2, q:"State what provides the centripetal force that keeps a planet in orbit around the Sun, and state the direction in which this force acts.",
    ms:["The gravitational attraction of the Sun on the planet (1)","It acts towards the centre of the orbit (towards the Sun) (1)"],
    trap:"Saying the force acts in the direction of motion. It acts at right angles to motion, towards the centre." },
  { cmd:"Describe", m:4, q:"Describe the life cycle of a star of similar mass to the Sun, from nebula to its final stage.",
    ms:["A nebula (cloud of gas and dust) collapses under gravity to form a protostar (1)","Fusion of hydrogen begins; the star becomes a stable main-sequence star (1)","When hydrogen runs out, it expands to become a red giant (1)","It sheds outer layers as a planetary nebula, leaving a white dwarf (1)"],
    trap:"Ending with a supernova or black hole. Those only happen to stars much more massive than the Sun." },
  { cmd:"Explain", m:2, q:"Explain what keeps a main-sequence star stable in size for billions of years.",
    ms:["Gravitational forces pull inwards, compressing the star (1)","Outward pressure from the energy released by nuclear fusion balances this, so the star is in equilibrium (1)"],
    trap:"Saying 'the forces cancel out' without naming both of them." },
  { cmd:"Define", m:2, q:"Explain what is meant by <b>redshift</b> of light from distant galaxies.",
    ms:["Light from the galaxy is shifted towards the red (longer wavelength / lower frequency) end of the spectrum (1)","This happens because the galaxy is moving away from us (1)"],
    trap:"Saying the galaxy 'looks red'. Redshift is a shift in the spectrum, measured using spectral lines." },
  { cmd:"Explain", m:3, q:"Explain how observations of redshift support the Big Bang theory.",
    ms:["Light from distant galaxies is redshifted, showing they are moving away from us (1)","More distant galaxies show greater redshift, so they are moving away faster (1)","This means the Universe is expanding, implying it began from a single point (1)"],
    trap:"Stopping at 'the universe is expanding'. You must complete the logic back to a single starting point." },
  { cmd:"State", m:2, q:"State what is meant by the terms <b>galaxy</b> and <b>the Universe</b>.",
    ms:["A galaxy is a large collection of billions of stars held together by gravity (1)","The Universe is all of space and everything in it, containing billions of galaxies (1)"],
    trap:"Using 'galaxy' and 'solar system' interchangeably. A solar system is one star and its planets." },
  { cmd:"Calculate", m:2, q:"A satellite orbits the Earth at a radius of 4.2 × 10⁷ m and completes one orbit in 24 hours.<br>Calculate its orbital speed. (Use v = 2πr/T)",
    ms:["T = 24 × 3600 = 86 400 s; v = 2π × 4.2 × 10⁷ / 86 400 (1)","v = 3.1 × 10³ m/s (1)"],
    trap:"Leaving T in hours. Convert to seconds for an answer in m/s." },
  { cmd:"Suggest", m:2, q:"Suggest why astronomers can learn what distant stars are made of without ever visiting them.",
    ms:["Each element absorbs or emits light at characteristic wavelengths, producing spectral lines (1)","By comparing the lines in starlight with known elements on Earth, the composition can be identified (1)"],
    trap:"Saying 'they use telescopes'. The question is about *how* the information is obtained, not the instrument." }
]
},

/* ==========================================================
   CHEMISTRY 5070
   ========================================================== */
chemistry: {

/* --- 0. Experimental chemistry --- */
0: [
  { cmd:"Describe", m:3, q:"Describe how you would separate a mixture of sand and salt to obtain dry samples of both.",
    ms:["Add water and stir to dissolve the salt (1)","Filter: sand is the residue, salt solution is the filtrate; wash and dry the sand (1)","Evaporate/crystallise the filtrate to obtain dry salt (1)"],
    trap:"Saying 'evaporate to dryness' for a salt you want as crystals. For pure crystals, evaporate to the point of crystallisation, then leave to cool." },
  { cmd:"Describe", m:2, q:"Describe how paper chromatography could show that a food colouring contains more than one dye.",
    ms:["Spot the colouring on a pencil baseline and place in solvent below the line; allow the solvent to rise (1)","If more than one spot appears at different heights, more than one dye is present (1)"],
    trap:"Drawing the baseline in ink. The ink itself would separate and ruin the result — it must be pencil." },
  { cmd:"Calculate", m:2, q:"In a chromatogram, the solvent front moved 8.0 cm and a dye spot moved 3.0 cm.<br>Calculate the Rf value of the dye.",
    ms:["Rf = distance moved by spot ÷ distance moved by solvent front (1)","Rf = 3.0/8.0 = 0.375 (accept 0.38) (1)"],
    trap:"Getting an Rf greater than 1. That is impossible — the spot can never move further than the solvent." },
  { cmd:"Describe", m:3, q:"Describe the test for an <b>ammonium</b> ion in an unknown solution, including the result.",
    ms:["Add aqueous sodium hydroxide to the solution and warm (1)","A gas is produced which turns damp red litmus paper blue (1)","This shows ammonia is released, so ammonium ions are present (1)"],
    trap:"Using dry litmus paper. The paper must be damp or the gas cannot dissolve and no colour change occurs." },
  { cmd:"State", m:3, q:"State the observations when aqueous sodium hydroxide is added, a little at a time and then in excess, to solutions containing (i) Cu²⁺, (ii) Zn²⁺, (iii) Fe³⁺.",
    ms:["Cu²⁺: light blue precipitate, insoluble in excess (1)","Zn²⁺: white precipitate, dissolves in excess to give a colourless solution (1)","Fe³⁺: red-brown precipitate, insoluble in excess (1)"],
    trap:"Not stating the 'in excess' behaviour. That second half is what distinguishes Zn²⁺ from other white precipitates." },
  { cmd:"Describe", m:2, q:"Describe the test for carbon dioxide gas.",
    ms:["Bubble the gas through limewater (calcium hydroxide solution) (1)","The limewater turns milky/cloudy (1)"],
    trap:"Saying 'it goes white'. The accepted words are milky or cloudy." },
  { cmd:"Describe", m:3, q:"Describe the test for chloride ions in solution, and state what you would see.",
    ms:["Add dilute nitric acid, then aqueous silver nitrate (1)","A white precipitate forms (1)","The acid is added first to remove carbonate ions which would also give a precipitate (1)"],
    trap:"Forgetting the nitric acid. Without it, carbonates give a false positive — and that is often the third mark." },
  { cmd:"Suggest", m:3, q:"A student wants to obtain pure water from seawater. Suggest a suitable method and explain how it works.",
    ms:["Simple distillation (1)","Heat the seawater; water boils and evaporates, leaving salts behind (1)","The vapour passes into a condenser where it cools and condenses to pure water (1)"],
    trap:"Saying 'filtration'. Dissolved salt passes straight through filter paper — filtering does nothing here." },
  { cmd:"Explain", m:2, q:"Explain why a fractionating column is needed to separate ethanol from water, rather than simple distillation.",
    ms:["Their boiling points are close together (78 °C and 100 °C) (1)","The column allows repeated evaporation and condensation, giving better separation of the two liquids (1)"],
    trap:"Saying ethanol 'boils first so it is easy'. If it were that easy, the column would not be needed." },
  { cmd:"State", m:2, q:"State the test for hydrogen gas and the test for oxygen gas.",
    ms:["Hydrogen: a lighted splint burns with a squeaky pop (1)","Oxygen: a glowing splint relights (1)"],
    trap:"Swapping them. Hydrogen needs a *lighted* splint; oxygen needs a *glowing* one." }
],

/* --- 1. The particulate nature of matter --- */
1: [
  { cmd:"Explain", m:3, q:"Explain, in terms of particles, why a gas fills any container it is placed in.",
    ms:["Gas particles are far apart with negligible forces of attraction between them (1)","They move rapidly and randomly in all directions (1)","So they spread out until evenly distributed throughout the container (1)"],
    trap:"Saying gases 'want to spread out'. Particles have no intention — describe the random motion instead." },
  { cmd:"Explain", m:2, q:"Ammonia gas and hydrogen chloride gas are released at opposite ends of a tube. A white ring forms nearer the hydrogen chloride end.<br>Explain why.",
    ms:["Ammonia has a lower relative molecular mass than hydrogen chloride (1)","Lighter molecules diffuse faster, so ammonia travels further before they meet (1)"],
    trap:"Saying ammonia 'is lighter so it rises'. This is about diffusion rate along the tube, not rising." },
  { cmd:"State", m:3, q:"An atom of chlorine is written as ³⁵₁₇Cl.<br>State the number of protons, neutrons and electrons it contains.",
    ms:["Protons = 17 (1)","Neutrons = 35 − 17 = 18 (1)","Electrons = 17 (1)"],
    trap:"Reading the top number as neutrons. The top number is protons + neutrons — you must subtract." },
  { cmd:"Describe", m:3, q:"Describe, using a dot-and-cross diagram in words, how sodium and chlorine form sodium chloride.",
    ms:["Sodium loses one electron from its outer shell to form Na⁺ (1)","Chlorine gains that electron to form Cl⁻ (1)","The oppositely charged ions attract by strong electrostatic forces, forming an ionic lattice (1)"],
    trap:"Saying they 'share' electrons. Sharing is covalent — ionic bonding is transfer." },
  { cmd:"Explain", m:3, q:"Explain why sodium chloride has a high melting point but does not conduct electricity when solid.",
    ms:["It has a giant ionic lattice with strong electrostatic forces between oppositely charged ions (1)","A lot of energy is needed to overcome these forces, so the melting point is high (1)","When solid, the ions are held in fixed positions and cannot move to carry charge (1)"],
    trap:"Saying 'there are no electrons free'. In ionic compounds it is the *ions* that must be free to move, not electrons." },
  { cmd:"Explain", m:3, q:"Both diamond and graphite are made only of carbon atoms. Explain why graphite conducts electricity but diamond does not.",
    ms:["In graphite each carbon atom forms three bonds, leaving one delocalised electron per atom (1)","These free electrons can move through the structure and carry charge (1)","In diamond each carbon forms four bonds, so there are no free electrons (1)"],
    trap:"Saying graphite is 'softer so electrons move'. Softness comes from weak forces between layers — a different property entirely." },
  { cmd:"Explain", m:2, q:"Explain why simple molecular substances such as carbon dioxide have low melting points.",
    ms:["The intermolecular forces between molecules are weak (1)","Only a little energy is needed to overcome them, although the covalent bonds inside molecules are strong (1)"],
    trap:"Saying 'the covalent bonds are weak'. Covalent bonds are strong — it is the forces *between* molecules that are weak." },
  { cmd:"Describe", m:3, q:"Describe the structure and bonding in a metal, and use it to explain why metals are good conductors of electricity.",
    ms:["A lattice of positive metal ions (1)","Surrounded by a 'sea' of delocalised electrons (1)","These electrons are free to move through the structure and carry charge (1)"],
    trap:"Forgetting to say the ions are positive. That is a separate mark point." },
  { cmd:"Explain", m:2, q:"Explain why alloys are usually harder than the pure metals they are made from.",
    ms:["The added atoms are a different size, disrupting the regular arrangement of layers (1)","Layers of ions cannot slide over each other as easily, so the alloy is harder (1)"],
    trap:"Saying 'the atoms bond more strongly'. The bonding is the same — it is the *arrangement* that changes." },
  { cmd:"State", m:2, q:"State what is meant by an <b>isotope</b>, and explain why isotopes of the same element have identical chemical properties.",
    ms:["Atoms of the same element with the same number of protons but different numbers of neutrons (1)","Chemical properties depend on the electron arrangement, which is the same for all isotopes (1)"],
    trap:"Saying they behave differently. Physically yes (mass, radioactivity), chemically no." }
],

/* --- 2. Formulae, stoichiometry and the mole --- */
2: [
  { cmd:"Calculate", m:2, q:"Calculate the relative formula mass of calcium carbonate, CaCO₃.<br>(Ar: Ca = 40, C = 12, O = 16)",
    ms:["40 + 12 + (3 × 16) (1)","= 100 (1)"],
    trap:"Multiplying only one oxygen. The subscript 3 applies to the oxygen only, giving 48." },
  { cmd:"Calculate", m:3, q:"Calculate the number of moles in 25 g of calcium carbonate, CaCO₃ (Mr = 100), and state how many molecules of CO₂ would be produced if it all decomposed.",
    ms:["moles = mass/Mr = 25/100 (1)","= 0.25 mol (1)","1:1 ratio, so 0.25 mol CO₂ = 0.25 × 6.0 × 10²³ = 1.5 × 10²³ molecules (1)"],
    trap:"Forgetting to use the mole ratio from the equation before converting to molecules." },
  { cmd:"Calculate", m:4, q:"A compound contains 40.0% carbon, 6.7% hydrogen and 53.3% oxygen by mass.<br>Calculate its empirical formula. (Ar: C = 12, H = 1, O = 16)",
    ms:["Divide by Ar: C = 40/12 = 3.33, H = 6.7/1 = 6.7, O = 53.3/16 = 3.33 (1)","Divide by the smallest (3.33): C = 1, H = 2, O = 1 (1)","Empirical formula = CH₂O (1)","Correct working shown throughout (1)"],
    trap:"Rounding too early. Keep at least two decimal places until the final ratio step." },
  { cmd:"Calculate", m:3, q:"What mass of magnesium oxide is formed when 4.8 g of magnesium burns completely in oxygen?<br>2Mg + O₂ → 2MgO (Ar: Mg = 24, O = 16)",
    ms:["moles Mg = 4.8/24 = 0.20 mol (1)","Ratio Mg:MgO is 2:2, so moles MgO = 0.20 (1)","mass = 0.20 × 40 = 8.0 g (1)"],
    trap:"Ignoring the balancing numbers. Always check the ratio in the equation before converting back to mass." },
  { cmd:"Calculate", m:3, q:"Calculate the volume of carbon dioxide, at room temperature and pressure, produced when 0.50 mol of calcium carbonate decomposes.<br>CaCO₃ → CaO + CO₂ (molar gas volume = 24 dm³/mol at rtp)",
    ms:["Ratio CaCO₃ : CO₂ is 1 : 1, so 0.50 mol CO₂ (1)","Volume = moles × 24 (1)","= 12 dm³ (1)"],
    trap:"Using 24 000 without converting units. 24 dm³ = 24 000 cm³ — state which one you are using." },
  { cmd:"Calculate", m:3, q:"25.0 cm³ of sodium hydroxide solution required 20.0 cm³ of 0.100 mol/dm³ hydrochloric acid for neutralisation.<br>Calculate the concentration of the sodium hydroxide. NaOH + HCl → NaCl + H₂O",
    ms:["moles HCl = 0.100 × 20.0/1000 = 2.00 × 10⁻³ mol (1)","Ratio 1:1, so moles NaOH = 2.00 × 10⁻³ mol (1)","concentration = 2.00 × 10⁻³ ÷ (25.0/1000) = 0.0800 mol/dm³ (1)"],
    trap:"Forgetting to divide volumes by 1000. Concentration is per dm³, but burette readings are in cm³." },
  { cmd:"Calculate", m:2, q:"In a reaction the theoretical yield was 12.0 g but only 9.0 g was obtained.<br>Calculate the percentage yield.",
    ms:["% yield = (actual/theoretical) × 100 = (9.0/12.0) × 100 (1)","= 75% (1)"],
    trap:"Inverting the fraction and getting more than 100%. Actual yield goes on top." },
  { cmd:"Explain", m:2, q:"Explain why the percentage yield of a reaction is often less than 100%.",
    ms:["Some product is lost during transfer, filtering or purification (1)","The reaction may be reversible or incomplete, or side reactions may occur (1)"],
    trap:"Saying 'atoms were destroyed'. Mass is always conserved — the product is lost, not destroyed." },
  { cmd:"Calculate", m:3, q:"Write the balanced equation for the complete combustion of methane, then calculate the mass of CO₂ produced from 8.0 g of methane. (Ar: C = 12, H = 1, O = 16)",
    ms:["CH₄ + 2O₂ → CO₂ + 2H₂O (1)","moles CH₄ = 8.0/16 = 0.50 mol; ratio 1:1 so 0.50 mol CO₂ (1)","mass CO₂ = 0.50 × 44 = 22 g (1)"],
    trap:"Forgetting the 2 in front of O₂. An unbalanced equation loses the mark even if the arithmetic is right." },
  { cmd:"Define", m:2, q:"Define the term <b>mole</b> and state the value of the Avogadro constant.",
    ms:["The amount of substance containing the same number of particles as there are atoms in 12 g of carbon-12 (1)","Avogadro constant = 6.0 × 10²³ per mole (1)"],
    trap:"Saying a mole is 'a mass'. It is an amount — a count of particles." }
],

/* --- 3. Electrolysis --- */
3: [
  { cmd:"Define", m:2, q:"Define <b>electrolysis</b> and explain what is meant by an <b>electrolyte</b>.",
    ms:["Electrolysis is the breakdown of an ionic compound, when molten or in aqueous solution, by the passage of electricity (1)","An electrolyte is a substance which conducts electricity when molten or dissolved, and is decomposed by it (1)"],
    trap:"Saying an electrolyte 'conducts electricity'. Metals do too — the key extra point is that it is *decomposed*." },
  { cmd:"State", m:3, q:"Molten lead(II) bromide is electrolysed.<br>State the product at each electrode and write the equation at the cathode.",
    ms:["Cathode: lead (a silvery molten metal) (1)","Anode: bromine (a red-brown vapour) (1)","Pb²⁺ + 2e⁻ → Pb (1)"],
    trap:"Getting the electrodes the wrong way round. Cations (positive) go to the cathode (negative)." },
  { cmd:"Explain", m:3, q:"Explain why lead(II) bromide conducts electricity when molten but not when solid.",
    ms:["When solid, the ions are held in fixed positions in the lattice (1)","When molten, the lattice breaks down and the ions are free to move (1)","Moving ions carry charge through the liquid, so it conducts (1)"],
    trap:"Saying 'electrons are free to move'. In electrolytes it is ions, not electrons, that carry the charge." },
  { cmd:"State", m:3, q:"Concentrated aqueous sodium chloride is electrolysed using inert electrodes.<br>State the product at each electrode and name the useful substance left in solution.",
    ms:["Cathode: hydrogen (1)","Anode: chlorine (1)","Sodium hydroxide remains in solution (1)"],
    trap:"Predicting sodium at the cathode. Hydrogen is less reactive than sodium, so hydrogen is discharged instead." },
  { cmd:"Explain", m:2, q:"Explain why hydrogen, and not sodium, is produced at the cathode during the electrolysis of aqueous sodium chloride.",
    ms:["Both H⁺ and Na⁺ ions are attracted to the cathode (1)","Hydrogen is below sodium in the reactivity series (less reactive), so H⁺ is discharged in preference (1)"],
    trap:"Saying 'there is more water'. Concentration matters at the anode, but at the cathode it is reactivity that decides." },
  { cmd:"Describe", m:3, q:"Describe how copper is purified by electrolysis, naming the electrodes and the electrolyte.",
    ms:["Anode: impure copper; cathode: pure copper (1)","Electrolyte: aqueous copper(II) sulfate (1)","Copper dissolves from the anode as Cu²⁺ and is deposited as pure copper on the cathode; impurities fall as sludge (1)"],
    trap:"Swapping the electrodes. The impure metal always dissolves, so it must be the anode." },
  { cmd:"Explain", m:3, q:"Explain why aluminium must be extracted by electrolysis rather than by reduction with carbon.",
    ms:["Aluminium is above carbon in the reactivity series (1)","So carbon cannot reduce aluminium oxide (1)","Electrolysis of the molten ore is used instead, with cryolite added to lower the melting point (1)"],
    trap:"Forgetting cryolite. It saves energy by lowering the melting point and is a standard mark point." },
  { cmd:"Explain", m:2, q:"In the extraction of aluminium, the carbon anodes must be replaced regularly. Explain why.",
    ms:["Oxygen is produced at the anode (1)","At the high temperature it reacts with the carbon anodes, burning them away as carbon dioxide (1)"],
    trap:"Saying they 'wear out'. You must say *why* — the oxygen burns them." },
  { cmd:"Describe", m:3, q:"Describe how you would electroplate an iron spoon with silver.",
    ms:["Cathode: the iron spoon; anode: pure silver (1)","Electrolyte: a solution containing silver ions, e.g. silver nitrate (1)","Silver ions are reduced and deposited on the spoon; the anode dissolves to replace them (1)"],
    trap:"Making the spoon the anode. The object being plated always goes at the cathode." },
  { cmd:"State", m:2, q:"State <b>two</b> reasons why objects are electroplated.",
    ms:["To improve appearance / make them more attractive (1)","To prevent corrosion / protect the metal underneath (1)"],
    trap:"Giving two versions of 'to look nice'. The two reasons must be genuinely different." }
],

/* --- 4. Energy from chemicals --- */
4: [
  { cmd:"Define", m:2, q:"Define an <b>exothermic</b> reaction and an <b>endothermic</b> reaction in terms of energy transfer.",
    ms:["Exothermic: energy is released/transferred to the surroundings, so the temperature rises (1)","Endothermic: energy is taken in from the surroundings, so the temperature falls (1)"],
    trap:"Saying exothermic 'produces heat'. Say transferred *to the surroundings* — that is the examiner's wording." },
  { cmd:"Explain", m:3, q:"Explain, in terms of bond breaking and bond making, why a reaction is exothermic.",
    ms:["Breaking bonds requires energy (endothermic) (1)","Making bonds releases energy (exothermic) (1)","In an exothermic reaction, more energy is released making bonds than is absorbed breaking them (1)"],
    trap:"Getting it backwards. Breaking always absorbs; making always releases. Learn it as one sentence." },
  { cmd:"Describe", m:2, q:"Sketch and describe an energy profile diagram for an exothermic reaction.",
    ms:["Products are at a lower energy level than reactants; ΔH is negative (1)","There is an energy 'hump' between them representing the activation energy (1)"],
    trap:"Omitting the activation energy hump. Even exothermic reactions need energy to start." },
  { cmd:"Define", m:1, q:"Define <b>activation energy</b>.",
    ms:["The minimum energy that colliding particles must have for a reaction to occur (1)"],
    trap:"Saying 'the energy needed to start the reaction' — accepted, but 'minimum energy for colliding particles' is safer." },
  { cmd:"Calculate", m:3, q:"In a reaction, 1400 kJ is absorbed breaking bonds and 1750 kJ is released forming bonds.<br>Calculate ΔH and state whether the reaction is exothermic or endothermic.",
    ms:["ΔH = energy in − energy out = 1400 − 1750 (1)","ΔH = −350 kJ/mol (1)","Exothermic, because ΔH is negative (1)"],
    trap:"Dropping the minus sign. The sign *is* the answer to the second half of the question." },
  { cmd:"State", m:2, q:"State what is meant by a <b>fuel</b> and give two examples of fossil fuels.",
    ms:["A substance which releases energy, usually as heat, when burned (1)","Any two: coal, crude oil (petroleum), natural gas (1)"],
    trap:"Naming petrol and diesel as fossil fuels. They are *products* of crude oil, not fossil fuels themselves." },
  { cmd:"Describe", m:3, q:"Describe how a hydrogen–oxygen fuel cell produces electricity, and state one advantage over petrol.",
    ms:["Hydrogen and oxygen are supplied continuously to the electrodes (1)","They react to form water, and the energy released produces an electric current (1)","Advantage: the only product is water, so no carbon dioxide or pollutants are produced (1)"],
    trap:"Calling it a battery. A fuel cell does not run down — fuel is fed in continuously." },
  { cmd:"Suggest", m:2, q:"Suggest two reasons why hydrogen fuel cells are not yet widely used in cars.",
    ms:["Hydrogen is difficult and expensive to store safely (it is a flammable gas under pressure) (1)","There are few refuelling stations, and producing hydrogen often requires fossil fuels (1)"],
    trap:"Saying 'it is dangerous' with no reason. Say *why* — it is flammable and stored under high pressure." },
  { cmd:"Explain", m:2, q:"Explain why photosynthesis is described as an endothermic process.",
    ms:["Energy from sunlight is absorbed by the plant (1)","This energy is stored in the chemical bonds of the glucose produced (1)"],
    trap:"Saying 'plants take in energy' without linking it to storage in chemical bonds." },
  { cmd:"Describe", m:3, q:"Describe an experiment to compare the energy released when two different fuels burn.",
    ms:["Burn a measured mass of each fuel under a fixed volume of water in a metal can (1)","Measure the temperature rise of the water for each fuel (1)","Keep distance, volume of water and container the same, so the comparison is fair (1)"],
    trap:"Forgetting the control variables. 'Fair test' points are almost always worth a mark here." }
],

/* --- 5. Chemical reactions --- */
5: [
  { cmd:"Explain", m:3, q:"Explain, using collision theory, why increasing the temperature increases the rate of a reaction.",
    ms:["Particles gain kinetic energy and move faster (1)","So they collide more frequently (1)","A greater proportion of collisions have energy above the activation energy, so more collisions are successful (1)"],
    trap:"Only saying 'they collide more often'. The energy point is a separate mark and is the one most students miss." },
  { cmd:"Explain", m:2, q:"Explain why powdered marble reacts faster with acid than a single lump of the same mass.",
    ms:["Powder has a much larger total surface area (1)","More particles are exposed to the acid, so there are more frequent collisions and a faster rate (1)"],
    trap:"Saying 'the powder is smaller'. It is the same mass — surface area is the point." },
  { cmd:"Define", m:2, q:"Define a <b>catalyst</b> and explain how it increases the rate of reaction.",
    ms:["A substance that increases the rate of a reaction and is unchanged chemically at the end (1)","It provides an alternative reaction pathway with a lower activation energy (1)"],
    trap:"Saying a catalyst 'lowers the activation energy'. Strictly it provides a *different pathway* which has a lower one." },
  { cmd:"Describe", m:3, q:"Describe how you could follow the rate of the reaction between marble chips and hydrochloric acid.",
    ms:["Measure the volume of carbon dioxide collected using a gas syringe at regular time intervals (1)","Or measure the loss in mass of the flask on a balance over time (1)","Plot a graph of volume (or mass lost) against time; the steeper the gradient, the faster the rate (1)"],
    trap:"Saying 'time how long it takes'. That gives one number — the question asks you to *follow* the rate over time." },
  { cmd:"Explain", m:2, q:"On a graph of gas volume against time, the curve becomes less steep and then flat. Explain why.",
    ms:["The reactants are being used up, so their concentration falls and collisions become less frequent (1)","The curve is flat when one reactant is completely used up and the reaction has stopped (1)"],
    trap:"Saying the reaction 'gets tired'. Concentration falling is the actual reason." },
  { cmd:"Define", m:2, q:"Define <b>oxidation</b> and <b>reduction</b> in terms of electrons.",
    ms:["Oxidation is the loss of electrons (1)","Reduction is the gain of electrons (1)"],
    trap:"Mixing them up. Remember OIL RIG: Oxidation Is Loss, Reduction Is Gain." },
  { cmd:"State", m:3, q:"In the reaction Zn + CuSO₄ → ZnSO₄ + Cu, state which species is oxidised, which is reduced, and which is the reducing agent.",
    ms:["Zn is oxidised (loses electrons to become Zn²⁺) (1)","Cu²⁺ is reduced (gains electrons to become Cu) (1)","Zn is the reducing agent (1)"],
    trap:"Assuming the oxidised species is the oxidising agent. It is the opposite — the species oxidised is the *reducing* agent." },
  { cmd:"Describe", m:2, q:"Describe a chemical test to show that a solution contains a reducing agent.",
    ms:["Add acidified potassium manganate(VII) solution (1)","The purple colour turns colourless (1)"],
    trap:"Saying it 'goes clear'. Colourless and clear are different — a solution can be clear and still coloured." },
  { cmd:"Explain", m:3, q:"Explain what is meant by a reaction being in <b>dynamic equilibrium</b>.",
    ms:["Both forward and reverse reactions are still occurring (1)","They occur at the same rate (1)","So the concentrations of reactants and products stay constant (1)"],
    trap:"Saying the reaction 'has stopped'. Nothing stops — that is exactly what 'dynamic' means." },
  { cmd:"Predict", m:2, q:"For the reaction N₂ + 3H₂ ⇌ 2NH₃ (forward reaction exothermic), predict and explain the effect of increasing the pressure on the yield of ammonia.",
    ms:["The yield of ammonia increases (1)","There are 4 molecules of gas on the left and 2 on the right, so the equilibrium shifts to the side with fewer molecules (1)"],
    trap:"Counting molecules wrongly. Add the coefficients on each side: 1 + 3 = 4 versus 2." }
],

/* --- 6. Acids, bases and salts --- */
6: [
  { cmd:"State", m:3, q:"State the three reactions of a dilute acid with (i) a metal, (ii) a base, (iii) a carbonate, giving the general products of each.",
    ms:["Metal: salt + hydrogen (1)","Base/alkali: salt + water (1)","Carbonate: salt + water + carbon dioxide (1)"],
    trap:"Forgetting that carbonate gives three products, not two. The CO₂ is the giveaway." },
  { cmd:"Explain", m:2, q:"Explain the difference between a <b>strong</b> acid and a <b>weak</b> acid.",
    ms:["A strong acid is completely (fully) ionised/dissociated in water (1)","A weak acid is only partially ionised in water (1)"],
    trap:"Saying a strong acid is 'more concentrated'. Strength and concentration are completely different ideas." },
  { cmd:"Describe", m:4, q:"Describe how you would prepare pure, dry crystals of copper(II) sulfate from copper(II) oxide and dilute sulfuric acid.",
    ms:["Warm the acid and add copper(II) oxide until no more dissolves (excess) (1)","Filter to remove the unreacted excess solid (1)","Heat the filtrate to the point of crystallisation, then leave to cool and crystallise (1)","Filter off the crystals and dry between filter papers (1)"],
    trap:"Evaporating to dryness. That gives powder, not crystals, and can decompose the salt." },
  { cmd:"Describe", m:3, q:"Describe how you would prepare a pure sample of insoluble barium sulfate.",
    ms:["Mix solutions of two soluble salts, e.g. barium chloride and sodium sulfate (1)","A precipitate of barium sulfate forms; filter it off (1)","Wash the residue with distilled water and leave to dry (1)"],
    trap:"Forgetting to wash the precipitate. Without washing it is contaminated with soluble salts." },
  { cmd:"Explain", m:2, q:"Explain why a titration must be used to prepare a pure sample of sodium chloride from sodium hydroxide and hydrochloric acid.",
    ms:["Both reactants are soluble, so excess solid cannot simply be filtered off (1)","Titration finds the exact volumes that react completely, leaving neither reactant in excess (1)"],
    trap:"Saying 'it is more accurate'. The real reason is that filtering is impossible when everything is soluble." },
  { cmd:"Define", m:2, q:"Define an <b>amphoteric oxide</b> and give one example.",
    ms:["An oxide that reacts with both acids and bases to form a salt and water (1)","Example: aluminium oxide or zinc oxide (1)"],
    trap:"Confusing amphoteric with neutral. Neutral oxides react with neither." },
  { cmd:"Explain", m:3, q:"A farmer's soil is too acidic. Explain how adding calcium hydroxide helps, and why too much would be a problem.",
    ms:["Calcium hydroxide is a base and neutralises the acid in the soil (1)","This raises the pH towards neutral, allowing crops to grow better (1)","Too much would make the soil alkaline, which is also unsuitable for most crops (1)"],
    trap:"Only answering the first half. When a question has two parts, both must be addressed." },
  { cmd:"Describe", m:3, q:"State the conditions used in the Haber process and write the equation.",
    ms:["N₂ + 3H₂ ⇌ 2NH₃ (1)","Temperature about 450 °C and pressure about 200 atmospheres (1)","Iron catalyst (1)"],
    trap:"Quoting exact numbers rigidly. Accept ranges — 400–450 °C is fine — but you must give a temperature, pressure and catalyst." },
  { cmd:"Explain", m:3, q:"Explain why a moderately high temperature is used in the Haber process, even though the forward reaction is exothermic.",
    ms:["A lower temperature would give a higher yield at equilibrium (1)","But the rate of reaction would be too slow to be economic (1)","So a compromise temperature gives a reasonable yield in a reasonable time (1)"],
    trap:"Only mentioning yield or only rate. The word 'compromise' is what earns the final mark." },
  { cmd:"State", m:2, q:"State the essential conditions of the Contact process for making sulfuric acid.",
    ms:["2SO₂ + O₂ ⇌ 2SO₃, at about 450 °C and 2 atmospheres (1)","Vanadium(V) oxide catalyst (1)"],
    trap:"Giving the Haber conditions instead. Contact uses V₂O₅ and a much lower pressure." }
],

/* --- 7. The Periodic Table --- */
7: [
  { cmd:"State", m:2, q:"State how the elements are arranged in the modern Periodic Table, and what the group number tells you.",
    ms:["In order of increasing proton (atomic) number (1)","The group number equals the number of electrons in the outer shell (1)"],
    trap:"Saying 'in order of mass'. Mendeleev did that; the modern table uses proton number." },
  { cmd:"Describe", m:3, q:"Describe and explain the trend in reactivity down Group I.",
    ms:["Reactivity increases down the group (1)","The outer electron is further from the nucleus and shielded by more inner shells (1)","So it is lost more easily, making the reaction faster (1)"],
    trap:"Forgetting shielding. Distance alone is usually only worth one of the two explanation marks." },
  { cmd:"Describe", m:3, q:"Describe what you would observe when a small piece of potassium is added to water.",
    ms:["It floats and melts into a ball, moving rapidly on the surface (1)","It burns with a lilac flame and may spark or explode (1)","It fizzes and disappears, producing hydrogen and an alkaline solution (1)"],
    trap:"Describing sodium's reaction. Potassium is more violent and has a lilac flame." },
  { cmd:"Describe", m:2, q:"Describe and explain the trend in reactivity down Group VII.",
    ms:["Reactivity decreases down the group (1)","The outer shell is further from the nucleus and more shielded, so an electron is gained less easily (1)"],
    trap:"Applying the Group I trend. Halogens *gain* electrons, so the trend is the opposite way round." },
  { cmd:"Predict", m:3, q:"Chlorine solution is added to potassium bromide solution.<br>Predict what happens, write the ionic equation, and explain in terms of reactivity.",
    ms:["The solution turns orange/brown as bromine is displaced (1)","Cl₂ + 2Br⁻ → 2Cl⁻ + Br₂ (1)","Chlorine is more reactive than bromine, so it displaces it from the compound (1)"],
    trap:"Writing the equation with full formulae rather than ions when an *ionic* equation is asked for." },
  { cmd:"State", m:3, q:"State the physical appearance of chlorine, bromine and iodine at room temperature.",
    ms:["Chlorine: pale green gas (1)","Bromine: red-brown liquid (1)","Iodine: grey-black solid (which sublimes to a purple vapour) (1)"],
    trap:"Just naming the colour. State the *state* as well — that is half the mark point." },
  { cmd:"Explain", m:2, q:"Explain why the noble gases are unreactive.",
    ms:["They have a full outer shell of electrons (1)","So they have no tendency to lose, gain or share electrons (1)"],
    trap:"Saying they have 'eight electrons'. Helium has only two, and it is still a noble gas." },
  { cmd:"State", m:3, q:"State three properties of transition elements that distinguish them from Group I metals.",
    ms:["They have higher melting points and densities (1)","They form coloured compounds (1)","They show variable oxidation states and act as catalysts (1)"],
    trap:"Saying 'they are metals'. Group I are metals too — the answer must be a *difference*." },
  { cmd:"Explain", m:2, q:"Explain why elements in the same group have similar chemical properties.",
    ms:["They have the same number of electrons in their outer shell (1)","Chemical properties are determined by the outer shell electrons (1)"],
    trap:"Saying 'they are in the same column'. That is a restatement, not an explanation." },
  { cmd:"Describe", m:2, q:"Describe the trend in metallic character across Period 3 from sodium to argon.",
    ms:["Elements change from metallic (Na, Mg, Al) to non-metallic (Si, P, S, Cl, Ar) (1)","So metallic character decreases across the period (1)"],
    trap:"Forgetting silicon is a metalloid, sitting between the two." }
],

/* --- 8. Metals --- */
8: [
  { cmd:"State", m:3, q:"State three physical properties common to most metals and explain one of them using metallic bonding.",
    ms:["Any three: good conductors of heat and electricity, malleable, ductile, shiny, high melting point (1)","Correct third property named (1)","Explanation, e.g. conduct electricity because delocalised electrons are free to move and carry charge (1)"],
    trap:"Listing properties but skipping the explanation. Read the second half of the question." },
  { cmd:"State", m:2, q:"Place these metals in order of decreasing reactivity: copper, magnesium, zinc, calcium.",
    ms:["Calcium, magnesium, zinc, copper (1)","Correct order maintained throughout (1)"],
    trap:"Reversing the order. 'Decreasing' means most reactive first." },
  { cmd:"Predict", m:3, q:"Predict what happens when zinc is added to copper(II) sulfate solution. Give the observation and the ionic equation.",
    ms:["Zinc is more reactive, so it displaces copper (1)","The blue solution fades and a brown/pink solid coats the zinc (1)","Zn + Cu²⁺ → Zn²⁺ + Cu (1)"],
    trap:"Forgetting the colour change of the solution. Both the solid and the solution change." },
  { cmd:"Explain", m:3, q:"Explain why iron is extracted using carbon but aluminium is not.",
    ms:["Iron is below carbon in the reactivity series, so carbon can reduce iron oxide (1)","Aluminium is above carbon, so carbon cannot reduce aluminium oxide (1)","Aluminium must therefore be extracted by electrolysis (1)"],
    trap:"Saying aluminium is 'too strong'. It is about reactivity order, nothing else." },
  { cmd:"Describe", m:4, q:"Describe the reactions occurring in the blast furnace, including the role of limestone.",
    ms:["Coke burns in hot air: C + O₂ → CO₂ (1)","CO₂ + C → 2CO, and CO reduces the ore: Fe₂O₃ + 3CO → 2Fe + 3CO₂ (1)","Limestone decomposes: CaCO₃ → CaO + CO₂ (1)","CaO reacts with sand impurities to form slag: CaO + SiO₂ → CaSiO₃ (1)"],
    trap:"Saying limestone 'removes impurities' without the two equations. Both steps are needed for both marks." },
  { cmd:"State", m:2, q:"State the two substances necessary for iron to rust, and name the product.",
    ms:["Oxygen (air) and water (1)","Product: hydrated iron(III) oxide (1)"],
    trap:"Saying just 'air'. You must specify oxygen — and water is equally essential." },
  { cmd:"Explain", m:3, q:"Explain how galvanising protects iron from rusting, and why the protection continues even if the coating is scratched.",
    ms:["The iron is coated with a layer of zinc, forming a barrier against air and water (1)","Zinc is more reactive than iron, so it loses electrons in preference (1)","This sacrificial protection continues even where the iron is exposed (1)"],
    trap:"Only giving the barrier answer. The scratch part of the question is specifically testing sacrificial protection." },
  { cmd:"Explain", m:2, q:"Explain why aluminium does not corrode easily despite being a reactive metal.",
    ms:["It reacts quickly with oxygen to form a thin layer of aluminium oxide on the surface (1)","This layer is unreactive and firmly attached, preventing further attack (1)"],
    trap:"Saying 'it is not really reactive'. It is very reactive — the oxide layer is what protects it." },
  { cmd:"Suggest", m:3, q:"Suggest three reasons why metals should be recycled.",
    ms:["Conserves limited ore reserves (1)","Uses much less energy than extracting from ore, so it is cheaper (1)","Reduces landfill waste and the environmental damage caused by mining (1)"],
    trap:"Giving three versions of 'it is good for the environment'. Each reason must be distinct." },
  { cmd:"Explain", m:2, q:"Explain why aluminium is used for aircraft bodies and copper for electrical wiring.",
    ms:["Aluminium has a low density and resists corrosion, keeping the aircraft light and durable (1)","Copper is an excellent conductor of electricity and is ductile, so it can be drawn into wires (1)"],
    trap:"Saying 'because it is a good metal'. Always name the specific property and link it to the use." }
],

/* --- 9. Atmosphere and environment --- */
9: [
  { cmd:"State", m:2, q:"State the approximate composition of clean, dry air.",
    ms:["About 78% nitrogen and 21% oxygen (1)","About 1% argon and other noble gases, with 0.04% carbon dioxide (1)"],
    trap:"Saying air is 'mostly oxygen'. Nitrogen dominates at nearly four-fifths." },
  { cmd:"State", m:3, q:"For each of carbon monoxide, sulfur dioxide and oxides of nitrogen, state one source and one harmful effect.",
    ms:["CO: incomplete combustion of fuels; toxic, combines with haemoglobin preventing oxygen transport (1)","SO₂: burning fossil fuels containing sulfur; causes acid rain (1)","NOₓ: formed in car engines at high temperature; causes acid rain and breathing problems (1)"],
    trap:"Giving the source without the effect. Each mark needs both halves." },
  { cmd:"Explain", m:3, q:"Explain how acid rain forms and describe two of its harmful effects.",
    ms:["Sulfur dioxide and nitrogen oxides dissolve in rainwater to form sulfuric and nitric acids (1)","Effect 1: damages trees and makes lakes acidic, killing fish (1)","Effect 2: corrodes limestone buildings, statues and metal structures (1)"],
    trap:"Saying carbon dioxide causes acid rain. CO₂ makes rain slightly acidic naturally, but acid rain means SO₂ and NOₓ." },
  { cmd:"Explain", m:3, q:"Explain how a catalytic converter reduces pollution from car exhausts, and give the equation.",
    ms:["It contains platinum/rhodium catalysts with a large surface area (1)","Carbon monoxide and nitrogen oxides react together (1)","2CO + 2NO → 2CO₂ + N₂ (1)"],
    trap:"Saying it 'filters out' the gases. It converts them chemically into harmless ones." },
  { cmd:"Explain", m:3, q:"Explain how the greenhouse effect leads to global warming.",
    ms:["Short-wavelength radiation from the Sun passes through the atmosphere and warms the Earth (1)","The Earth re-radiates longer-wavelength infrared radiation (1)","Greenhouse gases such as CO₂ and methane absorb this and re-emit it back, warming the atmosphere (1)"],
    trap:"Confusing the greenhouse effect with the ozone hole. They are separate problems with separate causes." },
  { cmd:"State", m:2, q:"State two greenhouse gases and one major source of each.",
    ms:["Carbon dioxide: burning fossil fuels / deforestation (1)","Methane: cattle farming, rice paddies, decomposing waste (1)"],
    trap:"Naming CFCs. They damage the ozone layer — a different issue." },
  { cmd:"Describe", m:2, q:"Describe the role of photosynthesis and respiration in the carbon cycle.",
    ms:["Photosynthesis removes carbon dioxide from the atmosphere and stores carbon in plants (1)","Respiration (and combustion and decomposition) returns carbon dioxide to the atmosphere (1)"],
    trap:"Only describing one direction. The cycle needs both removal and return." },
  { cmd:"Explain", m:3, q:"Explain how CFCs damage the ozone layer and why this matters.",
    ms:["CFCs rise into the stratosphere and are broken down by UV light, releasing chlorine atoms (1)","Chlorine atoms catalyse the breakdown of ozone molecules (1)","A thinner ozone layer lets more harmful UV reach the surface, increasing skin cancer risk (1)"],
    trap:"Saying CFCs 'make a hole'. Describe the chlorine mechanism to earn the marks." },
  { cmd:"Describe", m:3, q:"Describe the main stages of treating water to make it safe to drink.",
    ms:["Filtration through sand and gravel beds to remove solid particles (1)","Addition of chlorine to kill bacteria and other microorganisms (1)","Sedimentation, sometimes with added chemicals to make small particles clump together (1)"],
    trap:"Suggesting distillation. Far too expensive for a public water supply." },
  { cmd:"Suggest", m:2, q:"Suggest two ways a country could reduce its carbon dioxide emissions.",
    ms:["Use renewable energy sources such as solar, wind or hydroelectric instead of fossil fuels (1)","Improve energy efficiency, use public transport, or plant more trees (1)"],
    trap:"Saying 'stop pollution'. The answer must be a specific, realistic action." }
],

/* --- 10. Organic chemistry --- */
10: [
  { cmd:"Define", m:2, q:"Define a <b>homologous series</b> and state two characteristics of one.",
    ms:["A family of compounds with the same general formula and similar chemical properties (1)","Each member differs from the next by CH₂, and physical properties change gradually along the series (1)"],
    trap:"Saying 'they are all the same'. Chemical properties are similar; physical properties change gradually." },
  { cmd:"State", m:3, q:"State the general formula of the alkanes and alkenes, and explain what is meant by <b>saturated</b>.",
    ms:["Alkanes: CₙH₂ₙ₊₂ (1)","Alkenes: CₙH₂ₙ (1)","Saturated means the molecule contains only single carbon–carbon bonds (1)"],
    trap:"Mixing up the two formulae. Alkenes have fewer hydrogens because of the double bond." },
  { cmd:"Describe", m:2, q:"Describe a chemical test to distinguish between hexane and hexene.",
    ms:["Add aqueous bromine and shake (1)","Hexene decolourises the orange bromine water; hexane does not (1)"],
    trap:"Saying bromine 'turns clear'. Say decolourised — from orange to colourless." },
  { cmd:"Explain", m:3, q:"Explain what is meant by <b>cracking</b>, state the conditions used, and give one reason it is carried out.",
    ms:["Breaking large, less useful alkane molecules into smaller, more useful ones (1)","Conditions: high temperature with a catalyst (e.g. 600 °C, silica/alumina) (1)","It produces petrol-sized molecules and alkenes for making polymers, matching supply to demand (1)"],
    trap:"Confusing cracking with fractional distillation. Distillation separates; cracking breaks molecules apart." },
  { cmd:"Describe", m:3, q:"Describe how ethanol can be made by fermentation, stating the conditions.",
    ms:["Glucose solution with yeast added (1)","Warm (about 30–37 °C), in the absence of oxygen (anaerobic) (1)","C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂ (1)"],
    trap:"Forgetting 'no oxygen'. With oxygen you get vinegar, not ethanol." },
  { cmd:"Compare", m:3, q:"Compare making ethanol by fermentation with making it by hydration of ethene.",
    ms:["Fermentation uses a renewable resource (sugar) but is slow and gives impure ethanol (1)","Hydration uses ethene from crude oil (non-renewable) but is fast and continuous (1)","Hydration gives pure ethanol directly; fermentation is a batch process needing distillation (1)"],
    trap:"Only describing one method. 'Compare' means both, side by side." },
  { cmd:"State", m:2, q:"State the products when ethanol is oxidised, and name a suitable oxidising agent.",
    ms:["Ethanoic acid (and water) (1)","Acidified potassium dichromate(VI), or by bacteria in air (1)"],
    trap:"Saying carbon dioxide. That is complete combustion — oxidation here means forming the carboxylic acid." },
  { cmd:"Describe", m:3, q:"Describe how an ester is formed, naming the reactants and the catalyst.",
    ms:["An alcohol reacts with a carboxylic acid (1)","Concentrated sulfuric acid is used as a catalyst, and the mixture is warmed (1)","The products are an ester and water (1)"],
    trap:"Forgetting water is also formed. This is a condensation reaction." },
  { cmd:"Explain", m:3, q:"Explain how poly(ethene) is formed from ethene, and state why it is difficult to dispose of.",
    ms:["Many ethene molecules join together in addition polymerisation (1)","The double bonds open and the molecules link into a long chain, with no other product formed (1)","It is non-biodegradable, so it persists in landfill; burning it can release toxic gases (1)"],
    trap:"Calling it condensation polymerisation. Addition makes no second product — that is the difference." },
  { cmd:"State", m:2, q:"State the difference between addition and condensation polymerisation, giving one example of each.",
    ms:["Addition: monomers with C=C join with no other product, e.g. poly(ethene) (1)","Condensation: monomers join and a small molecule such as water is lost, e.g. nylon or Terylene (1)"],
    trap:"Not naming an example of each. The question asks for both." }
]
}

};

/* How many questions exist for a given subject and topic index */
function questionCount(subjectId, topicIndex) {
  const s = QUESTIONS[subjectId];
  if (!s || !s[topicIndex]) return 0;
  return s[topicIndex].length;
}
/* Does this subject have any questions at all yet? */
function hasQuestions(subjectId) {
  return !!QUESTIONS[subjectId];
}
